.TH cleanupdate 7 "17 August 2017"

.SH NOME
cleanupdate - aggiorna e pulisce del sistema

.SH DESCRIZIONE
cleanupdate è pensato per fornire un'interfaccia da terminale ma di semplice utilizzo per l'aggiornamento e la pulizia di un sistema operativo che utilizza
.B pacman
come gestore di pacchetti.

.SH OPZIONI
cleanupdate al momento non richiede alcuna opzione di utilizzo, nel caso in cui vengano forniti argomenti si interrompe restituendo un errore.
