.TH cleanupdate 7 "17 August 2017"
."
.SH NOME
cleanupdate - aggiorna e pulisce del sistema
."
.SH DESCRIZIONE
cleanupdate è pensato per fornire un'interfaccia da terminale ma di semplice utilizzo per l'aggiornamento e la pulizia di un sistema operativo che utilizza
.BR pacman "(8) "
come gestore di pacchetti.
."
.SS Aggiornamento del sistema
.PP
.B Aggiornamento dei pacchetti dai repository ufficiali:
Nel caso in cui il sistema installato sia Manjaro Linux viene aggiornata la lista dei mirror tramite
.BR pacman-mirrors "(8), "
se non è già stata aggiornata nel giorno corrente. Dopodiché effettua l'aggiornamento di tutti i pacchetti, tramite il comando 'pacman -Syu'. Il comando notifica se la versione installata di un pacchetto è più recente di quella nei repository, in questo caso dovrebbe venire proposto automaticamente un downgrade (abbassamento di versione) dei pacchetti problematici, tramite il comando 'pacman -Syuu'.
.PP
.B Aggiornamento dei pacchetti da AUR:
Effettua l'aggiornamento dei pacchetti provenienti dai repository AUR, se necessario. Può utilizzare come strumenti (in ordine di priorità)
.BR pacaur "(8) "
oppure
.BR yaourt "(8). "
Prima di controllare gli aggiornamenti lo script esegue un controllo per la presenza di pacchetti orfani, può essere utile nel caso in cui dei pacchetti installati come dipendenze vengano dismessi dai repository ufficiali di Arch Linux per essere trasferiti nei repository AUR.
."
.SH OPZIONI
cleanupdate al momento non richiede alcuna opzione di utilizzo, nel caso in cui vengano forniti argomenti si interrompe restituendo un errore.
